version: "3.5"

volumes:
  data-postgresql:
    driver: local
  data-directus:
    driver: local

services:

  redis:
    image: redis
    container_name: scammers.redis

  directus:
    container_name: scammers.directus
    restart: always
    image: directus/directus:${DIRECTUS_VERSION:-9.11.1}
    ports:
      - ${DIRECTUS_LISTEN:-8055}:8055
    volumes:
      - data-directus:/directus/uploads
    env_file:
      - ${DIRECTUS_ENV_FILE:-.directus.env}
    environment:
      KEY: ${DIRECTUS_ENV_KEY:-key}
      SECRET: ${DIRECTUS_ENV_SECRET:-secret}
      DB_CLIENT: pg
      DB_HOST: ${DIRECTUS_ENV_DB_HOST:-scammers.postgresql}
      DB_PORT: ${DIRECTUS_ENV_DB_PORT:-5432}
      DB_DATABASE: ${DIRECTUS_ENV_DB_DATABASE:-postgres}
      DB_USER: ${DIRECTUS_ENV_DB_USER:-postgres}
      DB_PASSWORD: ${DIRECTUS_ENV_DB_PASSWORD:-postgres}
      PUBLIC_URL: ${DIRECTUS_BASE_URI:-http://localhost:8055}
      AUTH_PROVIDERS: ${DIRECTUS_AUTH_PROVIDERS:-}
      CACHE_ENABLED: 'true'
      CACHE_TTL: 7d
      CACHE_AUTO_PURGE: 'true'
      CACHE_STORE: redis
      CACHE_REDIS: redis://scammers.redis:6379/2
      CACHE_NAMESPACE: i18n


  postgresql:
    image: postgis/postgis
    container_name: scammers.postgresql
    restart: always
    shm_size: '2gb'
    volumes:
      - data-postgresql:/var/lib/postgresql/data
    # ports:
    #   - ${POSTGRES_LISTEN:-127.0.0.1:5432:5432}
    environment:
      POSTGRES_PASSWORD:
      POSTGRES_DB:
      POSTGRES_USER:
      POSTGRES_HOST_AUTH_METHOD: ${POSTGRES_HOST_AUTH_METHOD:-trust}


  node:
    container_name: scammers.node
    image: node:16
    restart: unless-stopped
    environment:
      REDIS_URL:
      DIRECTUS_URL:
      DIRECTUS_TOKEN:
      PORT:
      REDIRECT_URL_IF_ERROR:
      CF_CLIENT_ID:
      CF_CLIENT_SECRET:
    volumes:
      - .:/app
      - ./node_modules:/app/node_modules
    working_dir: /app
    command: node app.js
    ports:
      - ${NODE_LISTEN:-127.0.0.1:3000:3000}




  # varnish:
  #   image: darioguarascio/varnish-elk-docker:latest
  #   container_name: scammers.varnish
  #   volumes:
  #     - data-varnish:/vcache:rw
  #     - ./config/varnish_backends.vcl:/usr/share/varnish/vcl/varnish_backends.vcl
  #   environment:
  #     ENV: ${ENV:-dev}
  #     VARNISHD_MEMORY: ${VARNISHD_MEMORY:-malloc,32m}
  #     VARNISH_PURGE_KEY: ${VARNISH_PURGE_KEY:-dev}

  #   healthcheck:
  #     test: ["CMD", "sh", "-c", "test -e /proc/`cat /varnish.pid` || (kill -s 15 -1 && (sleep 10; kill -s 9 -1)) " ]
  #     interval: 5s
  #     timeout: 1s
  #     retries: 1
  #     start_period: 5s
  #   logging:
  #     driver: syslog
  #     options:
  #       cache-disabled: "false"
  #       syslog-address: udp://${VARNISH_LOGGER_IP:-127.0.0.1}:${VARNISH_LOGGER_PORT:-5445}
  #   #     # syslog-format: "rfc3164"
  #   #     # tag: "node-red"
  #   restart: always
  #   ports:
  #     - ${VARNISH_LISTEN:-80}:80


