name: remote ssh command

on:
  push:
    branches:
      - main
jobs:
  deploy:
    name: Staging deploy
    runs-on: ubuntu-latest
    environment: staging
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USER }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          git pull
          npm i




